ARG version
FROM almalinux:9
ENV course="devops"\
    duration="120HRS"

ARG trainer="sreekanth"

ENV trainer=$trainer

RUN echo "Hi, Course is: ${course}, duration is: ${duration}, trainer is: ${trainer}, version: ${version}"
CMD ["sleep","2000"]  
